version: '3.8'

services:
  # MQTT GPS Collector Service
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-gps-collector
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - fleet-network
    depends_on:
      - redis
      - timescaledb
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MQTT Broker (Eclipse Mosquitto)

networks:
  fleet-network:
    driver: bridge
